# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
#图标来源 https://tablericons.com/

[[social]]
weight = 1
identifier = "github"
name = "GitHub"
url = "https://github.com/Hiyase"
[social.params]
icon = "brand-github"

[[social]]
weight = 2
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Hiyase_Nya"
[social.params]
icon = "brand-twitter"

[[social]]
weight = 3
identifier = "telegram"
name = "Telegram"
url = "https://t.me/END_Sen"
[social.params]
icon = "brand-telegram"

[[social]]
weight = 4
identifier = "mail"
name = "Mail"
url = "mailto:END.Send233@gmail.com"
[social.params]
icon = "mail"

[[social]]
weight = 5
identifier = "rss"
name = "RSS"
url = "index.xml"
[social.params]
icon = "RSS"
